---
title: "PML_Final_Project"
author: "Viswathish Dinesh"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Pre Analysis

## Load Libraries

```{r libraries, include=FALSE}
## Output has been muted to prevent unnecessary text
library(caret)
library(rpart)
library(rpart.plot)
library(randomForest)
library(gbm)
```

## Load Data

```{r import data}
training <- read.csv("data/pml-training.csv")
testing <- read.csv("data/pml-testing.csv")
```

## Data Cleaning

```{r data cleaning}
## Remove features with near-zero variance
NZV <- nearZeroVar(training)

training <- training[,-NZV]
testing <- testing[,-NZV]

## Remove features not contributing to accelerometer readings

col_rm <- grepl("^X|timestamp|user_name", names(training))
training <- training[, !col_rm]
testing <- testing[, !col_rm]

## Remove columns with a majority of missing values

na_cols <- sapply(training, function(x) mean(is.na(x))) > 0.95
training <- training[,!na_cols]
testing <- testing[,!na_cols]

## Set "classe" feature as factor
training$classe <- factor(training$classe)
```

# Creating the model

## Split the data into training and validation sets

```{r training v validation}
set.seed(12345) # Set seed for reproducibility
inTrain <- createDataPartition(training$classe, p = 0.70, list = FALSE)
train_data <- training[inTrain,]
valid_data <- training[-inTrain,]
```